export const WOJEWODZTWA = [
  "dolnośląskie",
  "kujawsko-pomorskie",
  "lubelskie",
  "lubuskie",
  "łódzkie",
  "małopolskie",
  "mazowieckie",
  "opolskie",
  "podkarpackie",
  "podlaskie",
  "pomorskie",
  "śląskie",
  "świętokrzyskie",
  "warmińsko-mazurskie",
  "wielkopolskie",
  "zachodniopomorskie",
] as const;

export const MIASTA_BY_WOJEWODZTWO: Record<string, string[]> = {
  "dolnośląskie": ["Wrocław", "Wałbrzych", "Legnica", "Jelenia Góra", "Lubin", "Głogów"],
  "kujawsko-pomorskie": ["Bydgoszcz", "Toruń", "Włocławek", "Grudziądz", "Inowrocław"],
  "lubelskie": ["Lublin", "Zamość", "Chełm", "Biała Podlaska", "Puławy"],
  "lubuskie": ["Zielona Góra", "Gorzów Wielkopolski", "Nowa Sól", "Żary"],
  "łódzkie": ["Łódź", "Piotrków Trybunalski", "Pabianice", "Tomaszów Mazowiecki", "Bełchatów"],
  "małopolskie": ["Kraków", "Tarnów", "Nowy Sącz", "Oświęcim", "Chrzanów", "Zakopane"],
  "mazowieckie": ["Warszawa", "Radom", "Płock", "Siedlce", "Pruszków", "Legionowo", "Ostrołęka"],
  "opolskie": ["Opole", "Kędzierzyn-Koźle", "Nysa", "Brzeg", "Kluczbork"],
  "podkarpackie": ["Rzeszów", "Przemyśl", "Stalowa Wola", "Mielec", "Tarnobrzeg", "Krosno"],
  "podlaskie": ["Białystok", "Suwałki", "Łomża", "Augustów", "Bielsk Podlaski"],
  "pomorskie": ["Gdańsk", "Gdynia", "Sopot", "Słupsk", "Tczew", "Starogard Gdański"],
  "śląskie": ["Katowice", "Częstochowa", "Sosnowiec", "Gliwice", "Zabrze", "Bytom", "Bielsko-Biała", "Rybnik", "Tychy"],
  "świętokrzyskie": ["Kielce", "Ostrowiec Świętokrzyski", "Starachowice", "Skarżysko-Kamienna"],
  "warmińsko-mazurskie": ["Olsztyn", "Elbląg", "Ełk", "Ostróda", "Iława", "Giżycko"],
  "wielkopolskie": ["Poznań", "Kalisz", "Konin", "Piła", "Ostrów Wielkopolski", "Gniezno", "Leszno"],
  "zachodniopomorskie": ["Szczecin", "Koszalin", "Stargard", "Kołobrzeg", "Świnoujście"],
};

export const KRAJE = [
  "Niemcy",
  "Holandia",
  "Belgia",
  "Wielka Brytania",
  "Francja",
  "Austria",
  "Szwajcaria",
  "Czechy",
  "Słowacja",
  "Włochy",
  "Hiszpania",
  "Szwecja",
  "Norwegia",
  "Dania",
  "Irlandia",
  "Portugalia",
  "Luksemburg",
  "Finlandia",
  "Grecja",
  "USA",
  "Kanada",
  "Australia",
  "Zjednoczone Emiraty Arabskie",
] as const;

export const MIASTA_BY_KRAJ: Record<string, string[]> = {
  "Niemcy": ["Berlin", "Monachium", "Hamburg", "Frankfurt", "Kolonia", "Düsseldorf", "Stuttgart", "Dortmund", "Essen", "Lipsk"],
  "Holandia": ["Amsterdam", "Rotterdam", "Haga", "Utrecht", "Eindhoven", "Groningen"],
  "Belgia": ["Bruksela", "Antwerpia", "Gandawa", "Brugia", "Liège"],
  "Wielka Brytania": ["Londyn", "Manchester", "Birmingham", "Liverpool", "Leeds", "Glasgow", "Edynburg"],
  "Francja": ["Paryż", "Marsylia", "Lyon", "Tuluza", "Nicea", "Nantes", "Strasburg"],
  "Austria": ["Wiedeń", "Salzburg", "Graz", "Innsbruck", "Linz"],
  "Szwajcaria": ["Zurych", "Genewa", "Berno", "Bazylea", "Lozanna"],
  "Czechy": ["Praga", "Brno", "Ostrawa", "Pilzno", "Liberec"],
  "Słowacja": ["Bratysława", "Koszyce", "Preszów", "Żylina", "Nitra"],
  "Włochy": ["Rzym", "Mediolan", "Neapol", "Turyn", "Florencja", "Wenecja", "Bolonia"],
  "Hiszpania": ["Madryt", "Barcelona", "Walencja", "Sewilla", "Malaga", "Bilbao"],
  "Szwecja": ["Sztokholm", "Göteborg", "Malmö", "Uppsala"],
  "Norwegia": ["Oslo", "Bergen", "Trondheim", "Stavanger"],
  "Dania": ["Kopenhaga", "Aarhus", "Odense", "Aalborg"],
  "Irlandia": ["Dublin", "Cork", "Galway", "Limerick"],
  "Portugalia": ["Lizbona", "Porto", "Faro", "Braga"],
  "Luksemburg": ["Luksemburg"],
  "Finlandia": ["Helsinki", "Espoo", "Tampere", "Turku"],
  "Grecja": ["Ateny", "Saloniki", "Patras", "Heraklion"],
  "USA": ["Nowy Jork", "Los Angeles", "Chicago", "Houston", "Miami", "Las Vegas"],
  "Kanada": ["Toronto", "Vancouver", "Montreal", "Calgary", "Ottawa"],
  "Australia": ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide"],
  "Zjednoczone Emiraty Arabskie": ["Dubaj", "Abu Zabi", "Szardża"],
};

// Dzielnice Wrocławia z przybliżonymi współrzędnymi
export const WROCLAW_DISTRICTS: Record<string, { lat: number; lng: number }> = {
  "Stare Miasto": { lat: 51.1100, lng: 17.0320 },
  "Śródmieście": { lat: 51.1080, lng: 17.0400 },
  "Nadodrze": { lat: 51.1200, lng: 17.0450 },
  "Ołbin": { lat: 51.1150, lng: 17.0550 },
  "Plac Grunwaldzki": { lat: 51.1120, lng: 17.0620 },
  "Biskupin": { lat: 51.0950, lng: 17.0800 },
  "Sępolno": { lat: 51.1020, lng: 17.0900 },
  "Krzyki": { lat: 51.0850, lng: 17.0200 },
  "Borek": { lat: 51.0780, lng: 17.0350 },
  "Huby": { lat: 51.0920, lng: 17.0280 },
  "Gaj": { lat: 51.0750, lng: 17.0500 },
  "Tarnogaj": { lat: 51.0680, lng: 17.0550 },
  "Fabryczna": { lat: 51.1050, lng: 16.9800 },
  "Grabiszyn": { lat: 51.0900, lng: 16.9900 },
  "Muchobór": { lat: 51.0950, lng: 16.9650 },
  "Popowice": { lat: 51.1100, lng: 16.9700 },
  "Pilczyce": { lat: 51.1180, lng: 16.9550 },
  "Psie Pole": { lat: 51.1400, lng: 17.0600 },
  "Karłowice": { lat: 51.1300, lng: 17.0450 },
  "Różanka": { lat: 51.1350, lng: 17.0350 },
  "Kowale": { lat: 51.1450, lng: 17.0750 },
  "Zakrzów": { lat: 51.1550, lng: 17.0850 },
};

// Miasta w okolicy Wrocławia (aglomeracja) z przybliżonymi współrzędnymi
export const WROCLAW_AREA_CITIES: Record<string, { lat: number; lng: number }> = {
  "Wrocław": { lat: 51.1079, lng: 17.0385 },
  "Oborniki Śląskie": { lat: 51.3050, lng: 16.9200 },
  "Trzebnica": { lat: 51.3100, lng: 17.0630 },
  "Oleśnica": { lat: 51.2100, lng: 17.3850 },
  "Środa Śląska": { lat: 51.1650, lng: 16.5950 },
  "Wołów": { lat: 51.3400, lng: 16.6400 },
  "Oława": { lat: 50.9450, lng: 17.2900 },
  "Strzelin": { lat: 50.7800, lng: 17.0650 },
  "Sobótka": { lat: 50.9300, lng: 16.7400 },
  "Kąty Wrocławskie": { lat: 51.0300, lng: 16.7700 },
  "Jelcz-Laskowice": { lat: 51.0400, lng: 17.3400 },
  "Brzeg Dolny": { lat: 51.2700, lng: 16.7150 },
  "Siechnice": { lat: 51.0350, lng: 17.1500 },
  "Długołęka": { lat: 51.1800, lng: 17.2000 },
  "Czernica": { lat: 51.0500, lng: 17.2200 },
  "Kobierzyce": { lat: 50.9850, lng: 16.9300 },
  "Żórawina": { lat: 51.0150, lng: 17.0500 },
  "Miękinia": { lat: 51.1550, lng: 16.7500 },
};

export const CATEGORY_ICONS: Record<string, string> = {
  "Prace fizyczne": "Hammer",
  "Sprzątanie": "Sparkles",
  "Przeprowadzki": "Truck",
  "Eventy": "PartyPopper",
  "Gastronomia": "UtensilsCrossed",
  "Ogród": "Flower2",
  "Transport": "Car",
  "Montaż i naprawy": "Wrench",
  "Opieka": "Heart",
  "Dostawy": "Package",
  "IT i komputery": "Laptop",
  "Inne": "MoreHorizontal",
};

export const JOB_STATUSES = {
  pending_payment: { label: "Oczekuje na płatność", color: "warning" },
  active: { label: "Aktywne", color: "success" },
  in_progress: { label: "W realizacji", color: "primary" },
  done: { label: "Zakończone", color: "muted" },
  archived: { label: "Archiwalne", color: "muted" },
  closed: { label: "Zamknięte", color: "destructive" },
} as const;

// Parkingi P+R we Wrocławiu ze współrzędnymi
export const WROCLAW_PARKINGS: Record<string, { lat: number; lng: number; capacity: number }> = {
  "PR01A - Psie Pole - Stacja PKP parking nr 1": { lat: 51.1413, lng: 17.0615, capacity: 100 },
  "PR01B - Psie Pole - Stacja PKP parking nr 3": { lat: 51.1403, lng: 17.0625, capacity: 150 },
  "PR02 - ul. Bystrzycka-Idzikowskiego (Kuźniki)": { lat: 51.0983, lng: 16.9431, capacity: 60 },
  "PR03A - Grabiszyn południe": { lat: 51.0876, lng: 16.9912, capacity: 80 },
  "PR03B - Grabiszyn północ": { lat: 51.0898, lng: 16.9895, capacity: 50 },
  "PR04 - ul. Snycerska-Majchra (Leśnica)": { lat: 51.1132, lng: 16.8893, capacity: 100 },
  "PR05 - ul. Sołtysowicka (Sołtysowice)": { lat: 51.1380, lng: 17.0180, capacity: 120 },
  "PR06 - ul. Krakowska (Krzyki)": { lat: 51.0720, lng: 17.0310, capacity: 200 },
  "PR07 - ul. Wołowska (Popowice)": { lat: 51.1150, lng: 16.9650, capacity: 80 },
  "PR08 - al. Hallera (Biskupin)": { lat: 51.0980, lng: 17.0850, capacity: 60 },
  "PR09 - ul. Kleczkowska (Nadodrze)": { lat: 51.1220, lng: 17.0380, capacity: 40 },
  "PR10 - ul. Bardzka (Jagodno)": { lat: 51.0450, lng: 17.0950, capacity: 100 },
};